# script for global depth plotting

table <- read.table("QC_all_maxD2000_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_all_maxD2000.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_all_maxD2000.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_all_maxD2000, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("QC_SR_48_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_SR_48_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_SR_48_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_SR_48_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("QC_NB_48_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_NB_48_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_NB_48_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_NB_48_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("QC_HC_48_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_HC_48_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_HC_48_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_HC_48_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("QC_ARN_47_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ARN_47_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ARN_47_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ARN_47_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("QC_COH_44_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_COH_44_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_COH_44_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_COH_44_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("QC_ref_48_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ref_48_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ref_48_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ref_48_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("QC_ch_50_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ch_50_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ch_50_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ch_50_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("QC_ch1_12_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ch1_12_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ch1_12_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ch1_12_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("QC_ch2_12_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ch2_12_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ch2_12_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ch2_12_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("QC_ch3_12_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ch3_12_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ch3_12_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ch3_12_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("QC_ch4_14_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ch4_14_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ch4_14_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ch4_14_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("QC_challenge_98_maxD2000_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_challenge_98_maxD2000.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_challenge_98_maxD2000.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_challenge_98_maxD2000, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("QC_wild_235_maxD2000_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_wild_235_maxD2000.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_wild_235_maxD2000.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_wild_235_maxD2000, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e7, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e7, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e7, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+70)], 1e7, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())
