# script for global depth plotting

table <- read.table("QC_all_maxD2000_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_all_maxD2000.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_all_maxD2000.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_all_maxD2000, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+90, 1e7, paste0("mean=", round(table$Mean)), col = "red")
abline(v = table$Mean+table$SD, col="red", lwd=3, lty=2)
text(table$Mean+table$SD+50, 1e7, "1xSD", col = "red")
abline(v = table$Mean+2*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+2*table$SD+50, 1e7, "2xSD", col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+50, 1e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+50, 1e7, "4xSD", col = "red")
invisible(dev.off())

table <- read.table("QC_SR_48_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_SR_48_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_SR_48_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_SR_48_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+12, 1e7, paste0("mean=", round(table$Mean)), col = "red")
abline(v = table$Mean+table$SD, col="red", lwd=3, lty=2)
text(table$Mean+table$SD+8, 1e7, "1xSD", col = "red")
abline(v = table$Mean+2*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+2*table$SD+8, 1e7, "2xSD", col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+8, 1e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+8, 1e7, "4xSD", col = "red")
invisible(dev.off())

table <- read.table("QC_NB_48_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_NB_48_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_NB_48_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_NB_48_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+12, 1e7, paste0("mean=", round(table$Mean)), col = "red")
abline(v = table$Mean+table$SD, col="red", lwd=3, lty=2)
text(table$Mean+table$SD+8, 1e7, "1xSD", col = "red")
abline(v = table$Mean+2*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+2*table$SD+8, 1e7, "2xSD", col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+8, 1e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+8, 1e7, "4xSD", col = "red")
invisible(dev.off())

table <- read.table("QC_HC_48_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_HC_48_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_HC_48_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_HC_48_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+12, 1e7, paste0("mean=", round(table$Mean)), col = "red")
abline(v = table$Mean+table$SD, col="red", lwd=3, lty=2)
text(table$Mean+table$SD+8, 1e7, "1xSD", col = "red")
abline(v = table$Mean+2*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+2*table$SD+8, 1e7, "2xSD", col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+8, 1e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+8, 1e7, "4xSD", col = "red")
invisible(dev.off())

table <- read.table("QC_ARN_47_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ARN_47_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ARN_47_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ARN_47_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+12, 1e7, paste0("mean=", round(table$Mean)), col = "red")
abline(v = table$Mean+table$SD, col="red", lwd=3, lty=2)
text(table$Mean+table$SD+8, 1e7, "1xSD", col = "red")
abline(v = table$Mean+2*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+2*table$SD+8, 1e7, "2xSD", col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+8, 1e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+8, 1e7, "4xSD", col = "red")
invisible(dev.off())

table <- read.table("QC_COH_44_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_COH_44_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_COH_44_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_COH_44_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+12, 1e7, paste0("mean=", round(table$Mean)), col = "red")
abline(v = table$Mean+table$SD, col="red", lwd=3, lty=2)
text(table$Mean+table$SD+8, 1e7, "1xSD", col = "red")
abline(v = table$Mean+2*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+2*table$SD+8, 1e7, "2xSD", col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+8, 1e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+8, 1e7, "4xSD", col = "red")
invisible(dev.off())

table <- read.table("QC_ref_48_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ref_48_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ref_48_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ref_48_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+12, 1e7, paste0("mean=", round(table$Mean)), col = "red")
abline(v = table$Mean+table$SD, col="red", lwd=3, lty=2)
text(table$Mean+table$SD+8, 1e7, "1xSD", col = "red")
abline(v = table$Mean+2*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+2*table$SD+8, 1e7, "2xSD", col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+8, 1e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+8, 1e7, "4xSD", col = "red")
invisible(dev.off())

table <- read.table("QC_ch_50_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ch_50_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ch_50_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ch_50_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+12, 1e7, paste0("mean=", round(table$Mean)), col = "red")
abline(v = table$Mean+table$SD, col="red", lwd=3, lty=2)
text(table$Mean+table$SD+8, 1e7, "1xSD", col = "red")
abline(v = table$Mean+2*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+2*table$SD+8, 1e7, "2xSD", col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+8, 1e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+8, 1e7, "4xSD", col = "red")
invisible(dev.off())

table <- read.table("QC_ch1_12_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ch1_12_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ch1_12_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ch1_12_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+6, 4e7, "mean", col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+6, 4e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+6, 4e7, "4xSD", col = "red")
invisible(dev.off())

table <- read.table("QC_ch2_12_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ch2_12_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ch2_12_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ch2_12_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+6, 4e7, "mean", col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+6, 4e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+6, 4e7, "4xSD", col = "red")
invisible(dev.off())

table <- read.table("QC_ch3_12_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ch3_12_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ch3_12_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ch3_12_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+6, 4e7, "mean", col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+6, 4e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+6, 4e7, "4xSD", col = "red")
invisible(dev.off())

table <- read.table("QC_ch4_14_maxD250_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_ch4_14_maxD250.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_ch4_14_maxD250.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_ch4_14_maxD250, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+6, 4e7, "mean", col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+6, 4e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+6, 4e7, "4xSD", col = "red")
invisible(dev.off())


table <- read.table("QC_challenge_98_maxD2000_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_challenge_98_maxD2000.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_challenge_98_maxD2000.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_challenge_98_maxD2000, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+70, 1e7, paste0("mean=", round(table$Mean)), col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+40, 1e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+40, 1e7, "4xSD", col = "red")
invisible(dev.off())

table <- read.table("QC_wild_235_maxD2000_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("QC_wild_235_maxD2000.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("QC_wild_235_maxD2000.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("QC_wild_235_maxD2000, mean=", round(table$Mean),", SD=",round(table$SD)))
abline(v = table$Mean, col="red", lwd=3, lty=2)
text(table$Mean+90, 1e7, paste0("mean=", round(table$Mean)), col = "red")
abline(v = table$Mean+table$SD, col="red", lwd=3, lty=2)
text(table$Mean+table$SD+50, 1e7, "1xSD", col = "red")
abline(v = table$Mean+2*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+2*table$SD+50, 1e7, "2xSD", col = "red")
abline(v = table$Mean+3*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+3*table$SD+50, 1e7, "3xSD", col = "red")
abline(v = table$Mean+4*table$SD, col="red", lwd=3, lty=2)
text(table$Mean+4*table$SD+50, 1e7, "4xSD", col = "red")
invisible(dev.off())
