# script for global depth plotting
###################### CHR pop #####################
table <- read.table("CHR_maf0.05_pctind0.7_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("CHR_maf0.05_pctind0.7.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("CHR_maf0.05_pctind0.7.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("CHR_maf0.05_pctind0.7_mask, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e4, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e4, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e4, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e4, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("CHR_maf0.05_pctind0.7_cv30_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("CHR_maf0.05_pctind0.7_cv30.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("CHR_maf0.05_pctind0.7_cv30.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("CHR_maf0.05_pctind0.7_cv30_mask, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e4, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e4, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e4, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e4, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

###################### WILD pop #####################
table <- read.table("WILD_maf0.05_pctind0.7_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("WILD_maf0.05_pctind0.7.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("WILD_maf0.05_pctind0.7.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("WILD_maf0.05_pctind0.7_mask, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e4, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e4, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e4, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e4, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("WILD_maf0.05_pctind0.7_cv30_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("WILD_maf0.05_pctind0.7_cv30.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("WILD_maf0.05_pctind0.7_cv30.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("WILD_maf0.05_pctind0.7_cv30_mask, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e4, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e4, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e4, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e4, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

###################### CH pop #####################
table <- read.table("CH_maf0.05_pctind0.7_cv30_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("CH_maf0.05_pctind0.7_cv30.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("CH_maf0.05_pctind0.7_cv30.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("CH_maf0.05_pctind0.7_cv30_mask, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e4, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e4, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e4, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e4, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())

table <- read.table("CH_maf0.05_pctind0.7_mask_mean_sd.log",sep = "", header = TRUE)
par(mfrow=c(1,1))
## global depth
jpeg("CH_maf0.05_pctind0.7_mask.jpg", width = 16, height = 8, units = 'in', res = 300)
dep <- as.numeric(scan(paste("CH_maf0.05_pctind0.7_mask.depthGlobal", sep="",collapse=""),what="char", quiet=T))
barplot(height=dep, names.arg=seq(1,length(dep))-1, xlab="Global Depth", ylab="Counts", main = paste0("CH_maf0.05_pctind0.7_mask_mask, mean=", round(table$Mean),", SD=",round(table$SD)))
locs <- as.numeric(barplot(dep, plot=FALSE))
abline(v = locs[round(table$Mean)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+35)], 1e4, "mean", col = "red")
abline(v = locs[round(table$Mean+table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+1*table$SD+25)], 1e4, "SD", col = "red")
abline(v = locs[round(table$Mean+2*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+2*table$SD+30)], 1e4, "2SD", col = "red")
abline(v = locs[round(table$Mean+3*table$SD)], col="red", lwd=3, lty=2)
text(locs[round(table$Mean+3*table$SD+65)], 1e4, paste0("3SD = ",round(table$Mean+3*table$SD)), col = "red")
invisible(dev.off())
